# permissions for end users to view notebooks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: notebook-viewer-role
rules:
- apiGroups:
  - pai.alibaba.com
  resources:
  - notebooks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pai.alibaba.com
  resources:
  - notebooks/status
  verbs:
  - get
